apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytriotaskflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytriotaskflaskapp
  template:
    metadata:
      labels:
        app: mytriotaskflaskapp
    spec: 
      containers:
      - name: mytriotaskflaskapp
        image: aolaad1/flaskapp:1.0
        ports: 
        - containerPort: 5000