apiVersion: v1
kind: Service
metadata:
  name: mytriotasksql
spec:
  type: ClusterIP # set the type of Service
  selector:
    app: mytriotasksql # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306